### ISSUE TITLE
SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate

### ISSUE THREAD

**Issue by itsvraju** [signalfx/built-in-dashboards#15]
I followed the README as mentioned in https://github.com/signalfx/built-in-dashboards
 
Note : I’m using us0 realm from my training class.
 
I’m trying to generate terraform template for –
 
Dashboard = > EVGpSi_AcAA belongs to groupId = > EVGpBh1AYAA
 
Command : python3 export_dashboards.py --key _yg71ya8HOhXHYkgUtS8CQ --dashboard EVGpSi_AcAA  --name sfx_aws_sqs_queue --output ./
 
 
I see the below error
 
```
Traceback (most recent call last):
  File "/Users/vraju/Documents/SF/built-in-dashboards/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/Users/vraju/Documents/SF/built-in-dashboards/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/Users/vraju/Documents/SF/built-in-dashboards/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/Users/vraju/Documents/SF/built-in-dashboards/venv/lib/python3.7/site-packages/urllib3/connection.py", line 360, in connect
    ssl_context=context,
  File "/Users/vraju/Documents/SF/built-in-dashboards/venv/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/Users/vraju/Documents/SF/built-in-dashboards/venv/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/vraju/Documents/SF/built-in-dashboards/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Users/vraju/Documents/SF/built-in-dashboards/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.us0.signalfx.com', port=443): Max retries exceeded with url: /v2/dashboard/EVGpSi_AcAA (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)')))
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "export_dashboards.py", line 161, in <module>
    dash_out = handle_dashboard(sfx, args['dash'], args['name'], args)
  File "export_dashboards.py", line 101, in handle_dashboard
    dash = sfx.get_dashboard(id)
  File "/Users/vraju/Documents/SF/built-in-dashboards/venv/lib/python3.7/site-packages/signalfx/rest.py", line 398, in get_dashboard
    **kwargs)
  File "/Users/vraju/Documents/SF/built-in-dashboards/venv/lib/python3.7/site-packages/signalfx/rest.py", line 142, in _get_object_by_name
    session=self._session, timeout=timeout)
  File "/Users/vraju/Documents/SF/built-in-dashboards/venv/lib/python3.7/site-packages/signalfx/rest.py", line 56, in _get
    response = session.get(url, timeout=timeout, params=params)
  File "/Users/vraju/Documents/SF/built-in-dashboards/venv/lib/python3.7/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/Users/vraju/Documents/SF/built-in-dashboards/venv/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/vraju/Documents/SF/built-in-dashboards/venv/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Users/vraju/Documents/SF/built-in-dashboards/venv/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.us0.signalfx.com', port=443): Max retries exceeded with url: /v2/dashboard/EVGpSi_AcAA (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)')))
 
 
Thanks,
 
Varun

**Comment by cory-signalfx** [comment]
Hey @itsvraju. 

This is very odd, as it's telling you there is a self-signed cert in the chain. That would break a lot of things beyond just this script. Do you have some sort of proxy in here?
